config/routes.rb
Rails.application.routes.draw do
  

  root 'flights#index'

  resources :bookings , only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, class_name: :Flight, foreign_key: :origin_airport_id
	has_many :arriving_flights, class_name: :Flight, foreign_key: :destination_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_many :passengers
	belongs_to :flight

	accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :destination_airport, class_name: :Airport
	belongs_to :origin_airport, class_name: :Airport
	has_many :flights
	has_many :bookings

	has_many :passengers, through: :bookings

	def self.available_dates
		flights = all.order(start_date: :asc)
		flights.map {|f| f.start_date_formatted}.uniq
	end

	def self.available_flights(params)
		parsed_date = parse_date(params[:start_date])
		where(origin_airport_id:params[:origin_airport_id], destination_airport_id: params[:destination_airport_id], start_date: parsed_date)
	end

	def self.parse_date(date)
		date_time = date.to_date
		date_time.beginning_of_day..date_time.end_of_day
	end
	
	def start_date_formatted
		start_date.strftime("%d/%m/%Y")
	end

	def flight_time
		start_date.strftime("%H : %M")
	end

	def airport(num)
		if num == 0
			return origin_airport.code
		elsif num == 1
			return destination_airport.code
		end
	end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def new
		@booking = Booking.new
		@flight = Flight.find(params[:flight_id])
		num_passengers = 	params[:passengers].to_i
		num_passengers.times do
			@booking.passengers.build
		end
	end


	def create
		@booking = Booking.new(booking_params)
		@flight = Flight.find(params[:booking][:flight_id])
		if @booking.save!
			PassengerMailer.welcome_email(@booking).deliver_now
			redirect_to @booking
			flash[:success] = "Booking successful"
		else
			flash[:warning] = "Booking failed"
			render "new"
		end
	end

	def show
		@booking = Booking.find(params[:id])
	end

	private

	def booking_params
		params.require(:booking).permit(:flight_id, passengers_attributes: %i[id name email])
	end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@airport_options = Airport.all.map { |a| [a.code, a.id]}
		@flight_dates = Flight.available_dates

		unless params[:commit].nil?
			@available_flights = Flight.available_flights(params)
		end
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= form_for @booking do |b| %>

<%= label_tag(:start_date, @flight.start_date_formatted ) %>

<%= label_tag(:flight_time, @flight.flight_time ) %>


<%= label_tag(:origin_airport, @flight.origin_airport.code ) %>

<%= label_tag(:destination_airport, @flight.destination_airport.code ) %>
<%= b.hidden_field :flight_id, value: @flight.id %>
<br>

<% passenger_num = 1 %>

<%= b.fields_for :passengers do |p_form| %>

<%= p_form.label(:passenger, "Passenger #{passenger_num}") %>
<br>
<%= p_form.label(:name, "Name") %>
<%= p_form.text_field(:name) %>
<br>
<%= p_form.label(:email, "Email") %>
<%= p_form.text_field(:email) %>
<br>
<% passenger_num += 1 %>

<% end %>

<%= submit_tag("Book Flight") %>

<% end %>

app/views/bookings/show.html.erb
<h1>Your Booking</h1>
<%= @booking.flight.origin_airport.code %>
<%= @booking.flight.destination_airport.code %>
<%= @booking.flight.start_date_formatted %>
<%= @booking.flight.flight_time %>
<br>
<% @booking.passengers.map do |p| %>
<%= "Name: #{p.name}" %> <br>
<%= "email: #{p.email}" %> <br>
<% end %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= form_tag(root_path, method: :get) do %>

<%= label_tag(:origin_airport_id, "Origin Airport")%>
<%= select_tag(:origin_airport_id, 
									options_for_select(@airport_options, 
																					params[:origin_airport_id])) %>

<%= label_tag(:destination_airport_id, "Destination Airport")%>
<%= select_tag(:destination_airport_id, options_for_select(@airport_options,params[:destination_airport_id])) %>

<%= label_tag(:start_date, "Start Date")%>
<%= select_tag(:start_date, options_for_select(@flight_dates, params[:start_date])) %>

<%= label_tag(:passengers, "No. of Passengers") %>
<%= select_tag(:passengers, options_for_select([1,2,3,4], params[:passengers])) %>

<%= submit_tag("Search") %>

<% end %>

<% if !params[:commit].nil? %>

 <% if @available_flights.any? %>
	<%= form_tag( new_booking_path, method: :get) do %>

	<% @available_flights.each do |f| %>

	<%= label_tag(:flight_id, f.origin_airport.code) %>
	<%= label_tag(:flight_id, f.destination_airport.code) %> 
	<%= label_tag(:flight_id, f.flight_time) %>
	<%= radio_button_tag(:flight_id, f.id) %>
	<br>
	<% end %>

	<%= hidden_field_tag(:passengers, params[:passengers]) %>
	<%= submit_tag("Choose Flight") %>

	<% end %>
	<% else %>

	<p>  No Available Flights </p>
		<% end %>
		<% else %>
	<p> Enter Details </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinFlightBooker</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>